Init commit
Ip-v/java-explore-with-me pull request #2
Opened 2022-11-15 06:32 UTC by Ip-v

2022-11-28 18:49 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        repository.save(cat);
метод `save` вернёт новую, сохранённую сущность, вот её и надо возвращать!

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        return CategoryMapper.toCategoryDto(category);
Есть хорошая практика делать отступ перед `return`.

Это выделяет точку выхода из метода визуально.
Есть только одно исключение: если метод начался сразу с return то отступ делать не нужно.

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        Category cat = repository.findById(catId).orElseThrow(() ->
Зачем мы тащили сущность и не использовали?
Если нужно выполнить просто проверку то создай метод `boolean isExist(Long id)`

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationAdminServiceImpl.java
> +            throw new ConditionsAreNotMetException(
Этот ексепшн часто используется но не фигурирует в `ErrorHandler` почему?
Какой код ответа возвращается клиенту?

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationPublicServiceImpl.java
> +        List<Compilation> list = pinned == null ? repository.findAll(pageRequest).getContent()
Подобное применение тернарников ужасно! 
Так куда понятнее

```
        if (pinned == null) {
            list = repository.findAll(pageRequest).getContent();
        } else if (pinned) {
            list = repository.findCompilationsByPinnedTrue(pageRequest);
        } else {
            list = repository.findCompilationsByPinnedFalse(pageRequest);
        }
```

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationPublicServiceImpl.java
> +        return list.stream().map(CompilationMapper::toCompilationDto).collect(Collectors.toList());
Лучше делать перенос каждой осмысленной операции на новую строку, когда мы комбинируем код в цепочку

```
        return list.stream()
                   .map(CompilationMapper::toCompilationDto)
                   .collect(Collectors.toList());
```

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/event/controller/EventPublicController.java
> +     * Это публичный эндпоинт, соответственно в выдаче должны быть только опубликованные события
Достойный JavaDoc!

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    public boolean equals(Object o) {
Equals и HashCode методы.

В данном случае, так как вы это не изучали лучше не переопределять эти два метода. 
В среднем случае приложению достаточно дефолтных реализаций. Но так же есть и те случаи кода требуется кастомная реализация, т. к. это может существенно увеличить производительность приложения, либо ухудшить, в случае если вы допустили ошибку.

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventPrivateServiceImpl.java
> +        update.setState(EventState.PENDING);
Во многих местах можно заимпортить статики, код получится компактнее и читабельнее...
`update.setState(PENDING);`

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/exceptions/ErrorHandler.java
> +        log.error("404 {}", e.getMessage());
Логируем со стек-трейсом
`log.error("404 {}", e.getMessage(), e);`

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/request/repository/EventRequestRepository.java
> +    @Query("select req from Request req left join Event as ev on req.event.id = ev.id " +
Пиши служебные слова SQL в верхнем регистре, во всех SQL скриптах...

2022-11-28 18:49 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/user/dto/UserDto.java
> +    //readonly = true
Местами встречаю закомменченные кусочки - подчисти код!

2022-11-29 06:22 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/MainServiceApp.java
> +public class MainServiceApp {
Привет!

2022-11-29 06:23 UTC, Ip-v commented on stats-service/src/main/resources/application.properties
> +server.port=9090
Переделал файл свойств в yml формат. Выглядит компактнее)

2022-11-29 06:34 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryService.java
> +    CategoryDto updateCategory(CategoryDto dto);
Поправил

2022-11-29 06:36 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        repository.save(cat);
Исправил

2022-11-29 06:37 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    public boolean equals(Object o) {
Ок

2022-11-29 06:59 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventPrivateServiceImpl.java
> +        update.setState(EventState.PENDING);
Заимпортил статикой

2022-11-29 07:00 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/exceptions/ErrorHandler.java
> +        log.error("404 {}", e.getMessage());
done

2022-11-29 07:18 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/request/repository/EventRequestRepository.java
> +    @Query("select req from Request req left join Event as ev on req.event.id = ev.id " +
Исправил

2022-11-29 07:30 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        return CategoryMapper.toCategoryDto(category);
Поправил

2022-11-29 07:32 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        Category cat = repository.findById(catId).orElseThrow(() ->
Поправил

2022-11-29 07:49 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationAdminServiceImpl.java
> +            throw new ConditionsAreNotMetException(
Добавил, код 403 FORBIDDEN

2022-11-29 07:51 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationAdminServiceImpl.java
> +            throw new ConditionsAreNotMetException(
403 не может фигурировать в нашем проекте, поскольку он говорит о недостаточности прав на ресурс... а у нас вообще не завезено security в проект!

2022-11-29 07:59 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationPublicServiceImpl.java
> +        return list.stream().map(CompilationMapper::toCompilationDto).collect(Collectors.toList());
Поправил

2022-11-29 07:59 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/user/dto/UserDto.java
> +    //readonly = true
Удалил лишнее

2022-11-29 08:03 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationPublicServiceImpl.java
> +        List<Compilation> list = pinned == null ? repository.findAll(pageRequest).getContent()
Поправил

2022-11-29 19:02 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-30 09:14 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationAdminServiceImpl.java
> +            throw new ConditionsAreNotMetException(
В спецификации 403 присутствует.

![image](https://user-images.githubusercontent.com/26865859/204755251-4d478ed6-32e4-4a53-840b-d94a68238e79.png)

2022-11-30 09:15 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationAdminServiceImpl.java
> +            throw new ConditionsAreNotMetException(
Спасибо что подсветил!
Тогда моё замечание не актуально конечно...

2022-11-30 16:55 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryService.java
> +    CategoryDto update(CategoryDto dto);
Сходство есть между интерфейсами. Но объединять, на мой взгляд, не целесообразно.  При объединении сломается логика разделения сущностей по уровню доступа.
Например, по спецификации метод add есть у админа для категорий, но отсутствует для событий. И так с большинством эндпоинтов.

2022-12-01 07:45 UTC, Ip-v commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventAdminServiceImpl.java
> +        return eventRepository.findAll(searchCriteria, pageable)
Действительно страшное(( Поправил

2022-12-01 07:48 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/event/service/EventAdminServiceImpl.java
> +        return eventRepository.findAll(searchCriteria, pageable)
))

2022-12-01 17:43 UTC, FanaticFiz commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryService.java
> +    CategoryDto update(CategoryDto dto);
Да, поэтому интерфейсы должны дробиться чтобы не было такого что кто-то не имплементит часть методов...

2022-12-01 17:44 UTC, FanaticFiz approved these changes

2022-12-02 07:37 UTC, merged